name := "diamonds"
version := "1.0"
scalaVersion := "2.12.12"
//libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.0.1"
//libraryDependencies += "org.apache.spark" %% "spark-ml" % "2.12" 
//libraryDependencies += "org.apache.spark" %% "spark-mllib_2.12" % "3.0.1"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "3.0.1"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.0.1"
libraryDependencies += "org.apache.logging.log4j" %% "log4j-api-scala" % "11.0"

